spring.application.name=main
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG

spring:
autoconfigure:
exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration

spring.data.mongodb.uri=mongodb+srv://jaruwith2710_db_user:7hltQM4fyXaHwsJc@lastopusservice.t4ivpfi.mongodb.net/?appName=LastOpusService
server.port=8081

